language: java
script:
- mvn clean package
deploy:
  provider: heroku
  api_key:
    secure: GBeoTvAc7RP9RwEHdhZiEhvM+jpSIw+y3B2ODf0NF7yHxUlREjS2du55FpAUnHfHt3nPM1q2hjmCCwHNCLANqSsUBU8gEy+jWGX7vbVEWg/ZoMIVSjjV4p/QaUiGZz2VkL6YuowZd2a0lTcWw2fSRE5aKesdDJpzP7h+lWOGWbuN9iasTOxAGxOymCM6SN4fDL65Hdt6SbpyN1Mtn3OJfcOwf72brRsfGGscUQaK5UQNZVnHmU6A9obmdmNU2MXk5jMtVlrtvn0SG3k6IRIqUDGKPSiq3dxKo55Z2HY70ZDGwjlZ4EgJ4WV+VwFYeMRWblm2IWX2kYLB7tp/+2Lk0i+lEn6+HZW0q7ETkEYcuXJHristdMCNwBMUxFfUtAtfrypjb3mMH22NhIiIpjAz5h730owAHFKj0MkIP43Sm7p0uBckEzTND3k83aFIrzxV5C2L9D//wWzytv1hARbJIriZuwtwdsoYFQIZnVzLkoE90xdfnYe5XYmdXo8JKv8dQtMm4qENG8jxIEag2p9N9zyxq+RuFPMmFXz9FCLxtrJiYb7k4Jj5Vz7aTY8VpaS6f6bsdq+7pNaHFuRqhlh0OqE5dTN1JcAegc43XYkhZ5Mag0qc8g0TOD8SjRT0s1uTYdFW+WR1Q8LIUMZaIiqjxB8Hn6AltGvxphhUPujyd2Q=
  app:
    master: laba5project19
    khutsanu-branch: khutsanu-branch